name: Unzip File

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Check file existence
        run: |
          echo "=== Root Directory Content ==="
          ls -la

      - name: Unzip file
        run: |
          unzip lvbl-infinity-extension.zip -d extracted_folder/

      - name: Commit and push extracted files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add extracted_folder/
          git commit -m "Unpack ZIP archive" || echo "No changes to commit"
          git push
